# Generated by Django 2.1.7 on 2019-05-31 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuBoardName', models.CharField(max_length=20)),
                ('menuBoardID', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopID', models.PositiveIntegerField()),
                ('shopName', models.CharField(max_length=30)),
                ('masterName', models.CharField(max_length=10)),
                ('openDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='menuboard',
            name='shopID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Shop'),
        ),
    ]
