# Generated by Django 2.1.7 on 2019-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20190601_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuboard',
            name='menuBoardID',
            field=models.PositiveIntegerField(),
        ),
    ]
