# Generated by Django 2.1.7 on 2019-06-10 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_auto_20190609_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='masterName',
        ),
    ]
