# Generated by Django 2.1.7 on 2019-06-16 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0007_auto_20190610_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.PositiveIntegerField(unique=True)),
                ('munuBoard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.MenuBoard')),
            ],
        ),
    ]
