# Generated by Django 2.1.7 on 2019-06-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderingQueue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordernumber',
            old_name='munuBoard',
            new_name='menuBoard',
        ),
    ]
