# Generated by Django 2.1.7 on 2019-05-24 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MenuBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuBoardID', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopID', models.PositiveIntegerField()),
                ('shopName', models.CharField(max_length=30)),
                ('masterName', models.CharField(max_length=10)),
                ('openDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='menuboard',
            name='shopID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Shop'),
        ),
        migrations.AddField(
            model_name='category',
            name='menuBoard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MenuBoard'),
        ),
    ]
