# Generated by Django 2.1.7 on 2019-06-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190603_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='quantity',
        ),
    ]
